[package]
name = "babel-schema"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
babel-api.workspace = true
babel-authoring.workspace = true
babel-capabilities.workspace = true
babel-crypto.workspace = true
babel-discovery.workspace = true
babel-graph.workspace = true
babel-hashgraph.workspace = true
babel-identity.workspace = true
babel-judgment.workspace = true
babel-lens.workspace = true
babel-media.workspace = true
babel-network.workspace = true
babel-node.workspace = true
babel-object.workspace = true
babel-personalization.workspace = true
babel-realtime.workspace = true
babel-rpc.workspace = true
babel-runtime.workspace = true
babel-state.workspace = true
babel-types.workspace = true
hex.workspace = true
schemars.workspace = true
serde.workspace = true
serde_json.workspace = true

[dev-dependencies]
tempfile = "3.23.0"
