[package]
name = "babel-capabilities"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
babel-object.workspace = true
babel-types.workspace = true
serde.workspace = true
serde_json.workspace = true
schemars.workspace = true
time.workspace = true
rand_core.workspace = true

[dev-dependencies]
babel-crypto.workspace = true
babel-identity.workspace = true
